---
title: "Easy website with Rstudio + Github tutorial"

author: JA Moggridge
date: 2020/03/07
---
<br>

---

# Overview  
***
**If you want to make a "your.name.github.io" website with Rstudio like this one**, then you are in luck. The process is fairly simple (famous last words, I know). It helps if you're a bit familiar with Rstudio's Markdown format used in notebooks; if not, this is a good [walk-through](https://seb951.github.io/rmarkdown_workshop/Rmarkdown/rmarkdown_main.html).  

Rstudio has a great variety of tools to analyze, represent and communicate scientific information; 
I'm looking to leverage these here to produce work that is both informative and aesthetic but also readily reproducible. I'm already a big fan of working with R notebooks and Jupyter, so going this route felt natural.


Rstudio has their own tutorial on their website about making websites but the simplest how-to I found was on [Florian Privé's github](https://github.com/privefl/rmarkdown-website-template#make-your-website-with-r-markdown-in-minutes).  This tutorial demonstrates how to copy his templates and put your version up on github.

For more guidance on structuring and Rmarkdown formatting, I learned a lot from [Emily Zabor's site](https://www.emilyzabor.com/tutorials/rmarkdown_websites_tutorial.html#personal_websites)
<br>

<br>

---
## Instructions
***
<br>

####  **Install** if necessary


***

  +  R and Rstudio (I'm using R v3.6.2 and v1.2)  
  
  +  Git and a Github account  
  
  +  a fewR packages:  
  
      *  to install a package: $ R install.packages("Package_Name_Here")  
  
      *  devtools -> I had to install this when the 'Build' menu only had the 'Configure built tools...' option.  
  
      *  tidyverse  
<br>

<br>


####  Get a ready-made **template**

***
  
+  **Go to [Florian Privé's github repository](https://github.com/privefl/rmarkdown-website-template#make-your-website-with-r-markdown-in-minutes).**  Follow his instructions to:


+ **Fork** his GitHub repository for the webpage to yours

+ Rename the repository it to **yourname**.github.io 
  
+ Once in your github, click ‘Clone’, choose ‘SSH key’ not http. **Copy the key**

  * You might need to create a new SSH key for Git (I did & have included instructions on how to do this below this section; it wasn't hard).  
<br>

<br>


#### Create your **building environment**

***    
  + Open a **new project** from file menu
  
  + Choose **version control** option
  
  + Choose **Git** option
  
  +  Your repository info should paste from the clipboard into the fields
  
  + Choose a directory & save. All the files you'll need to build the site should now be downloaded and imported to your Rstudio environment for editing.

<br>  
  
####  **Key files** --  *\_site.yml* and *index.Rmd*  
***  
  + Open these in the 'files' pane in Rstudio
  
  + **_site.yml** file defines the layout of the site. This is where you can:
  
    * Add your own info to the template
    
    * Set pages themes  
  
    * Add new pages to menus  <p>  <p>
    
    
  + **index.Rmd** is the current frontpage of the site, given the setup in the _site.yml file. The **about.Rmd** is an extra page that is further down in the menu
    
    * These are Rmarkdown documents, you can edit their content and then they will be rendered into html files before you build the website.<p>
    
  *  Once you're done adding and editing, and you want to upload it, save your files, go to the 'Build' tab and click 'Build Website'
  
  
  
<br>  

#### **Git** add, commit and push to finish
<br>  

There are probably other ways to do this but using terminal is fast and easy.  

* Open a terminal window, set working directory to your project folder

* Enter these commands in (after $):

\list \of \Git \commands \to \add \commit \push

        if you to see a list of Git commands (optional, shows documentation for Git):
           $ git
           
        this adds all the files in the directory to the index  
           $ git add .
           
        this records all the changes that were made and labels this version "first build"  
           $ git commit -m "first build"
           
        a summary of the changes you made will be printed in the window.
        next you can use the push command to finalize your changes
           $ git push
        
        (you can also do these things in the 'Git' tab of Rstudio)
<br>

**Your site should now be up on yourname.github.io. Nice!**

<br>  

<br>  

***

# Troubleshooting
  
***  

#### If you need a new SSH key on Github  
<br>
I followed [this tutorial](https://help.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) to generate a new SSH key on Github for the first time.

While doing that, you might run into an issue with this if you are on macOS > 10.12. (see next section)
<br>  

  
***
#### Problem encounter while setting SSH key for Github to Rstudio:
<br>  

I get to this step where I need to modify the ‘.ssh/config’ file:  
      
    If you're using macOS Sierra 10.12.2 or later, you will need to modify your ~/.ssh/config file to automatically load keys into the ssh-agent and store passphrases in your keychain.
            
            Host *
              AddKeysToAgent yes
              UseKeychain yes
              IdentityFile ~/.ssh/id_ra

I’m using OSx10.12.6, so I found a good answer on StackOverflow and do this stuff
    
        Start Terminal and create the ~/.ssh directory if it doesn't exist:
        	$ mkdir -p ~/.ssh
        
        Now go into the directory:
        	$ cd ~/.ssh
        
        Now open the file config with the default editor:
        	$ open -t config
        
        If it says that file doesn't exist, create it with:
        	$ touch config
        
        and try opening again:
         	$ open -t config
        
        When you edit the file, make sure it is "Plain Text" using the menu at the top of the screen and clicking Format->Make Plain Text.
        Set the permissions as instructed in your tutorial.

Finish that GitHub tut and go to the next page to copy SSH info and add it into Github.
This was fine using this:

    	This copies the contents of the id_rsa.pub file to your clipboard
        	$ pbcopy < ~/.ssh/id_rsa.pub
    
Now I can ‘Clone’ the repository by copying the SSH link from my github repository jmoggridge.github.io

<br>  	
  
----  
##  Notes to myself & things I wish I knew
     
***  

<br>
I keep this list as an *aide-memoire* to come back to when I encounter the same problem I've already had instead of combing stackoverflow. Notes are added when I figure out how to do something that I will probably forget again.

*first build: 2020/03/07*

*  had to re-install devtools to get the 'Build' function working in Rstudio
*  

