---
title: "Basic website with Shiny and hosting on Github"
output: 
  html_document:
    toc: true
    toc_float:
      toc_collapsed: false
    toc_depth: 6
    theme: lumen
    # number_sections: true
---


---
    
  
### Guides  

- Basic tutorial and example [Florian Privé's github](https://github.com/privefl/rmarkdown-website-template#make-your-website-with-r-markdown-in-minutes). 
- For more on structuring and Rmarkdown formatting: [Emily Zabor's site](https://www.emilyzabor.com/tutorials/rmarkdown_websites_tutorial.html#personal_websites)
  
---

### Instructions  
  
---

First make sure that your github account is setup.
     
#### 1. Setup R environment  
  
+  **Install/reinstall** if necessary:
   *  R, Rstudio, Git (and SSH key; possibly install xcode on mac), Shiny, devtools, tidyverse  
   *  note on devtools -> I had to reinstall this when the 'Build' menu only had the 'Configure built tools...' option for Shiny to render html documents. Reinstalling devtools solved the issue   

+  Create your **building environment** in Rstudio

+  Open a **new project** from file menu  

  *  Choose **version control** option  
  *  Choose **Git** option  
  *  Your repository info should paste from the clipboard directly into the fields otherwise copy/paste.
  *  Choose a directory & save. All the files you'll need to build the site should now be downloaded and imported to your Rstudio environment for editing.  
  
---  
  
#### 2. Create files
  
-  Create two files in Rstudio: "_site.yml" (txt file) and "index.Rmd".

   +  "_site.yml" file defines the layout and themes of the site.
   +  "index.Rmd" is the content of the site.
  
---  
  
#### 3. Add content and add structure
    
[Basic documentation for authoring Rmarkdown](https://rmarkdown.rstudio.com/authoring_basics.html)   
[Cheatsheet for Rmarkdown](https://rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)


*  ##### Rmarkdown text:
   -  Add to body of index.Rmd (or other linked .Rmd) 
   -  Use `<br><br>` to add extra line breaks. 
   -  Embed other elements in text: links, pictures.  
   -  Use 2 spaces at end of line to start a new line. 
   -  Enclose text with single asterisk for *italics* or two for **bold** face.  
   -  Use hash signs \# to create nesting headers   
   -  Use \\$ to enclose math expressions written with mathjax syntax:  
      -  $0 = e^{i*\pi}+1$    
  <br>     
     
*  ##### Hyperlinks to other pages, including between different pages on your site:
   - within site to other .html documents: `[text to appear on page](filename.html)`  
   - URLs: `[text to appear](http://www.URL.com)`     <br><br>
   
*  ##### Navigation bar header:
   -  for single page: add `toc` to header of .Rmd file  
   -  for entire website: need to edit `navbar` in _site.yml file, eg.:

```
  navbar:
    type: inverse
    left:
      - icon: fa-home
        text: Home
        href: index.html
    right:
      - text: Code
        icon: fa-github
        href: https://github.com/jmoggridge
      - text: Email
        icon: fa-envelope-o
        href: mailto:ja.moggridge@gmail.com
      - icon: fa-twitter fa-lg
        href: https://twitter.com/quaxlikeaduck
```
   
*  ##### Code blocks like above:    
   -  for line: enclose with backticks    
   -  for multiple lines, create a code chunk with three  backticks. Or just use the add chunk command and remove the `{r}` from the header of the chunk to make it just echo the code and not try to interpret it.
  
   <br>
   
*  ##### Create pages beyond the homepage (index.Rmd):
   -  Need to create new Rmd file  
   -  Create content as for index file above.
   -  'Knit' .Rmd file to render .html document.
   -  Add a link to the html file in text using the filename as above.  
    
<br>
      
*   ##### Social media icons and links in the header
    Done through the _site.yml file in the navbar section (as above). As with links, href can be an html file that you add to the repository or an address.

   <br>


- ##### Lists 
  -  Easy to make but can be difficult to get spacing right         
    +  Use a symbol `* - +` and two spaces to start                     
    +  Add next item with same indentation    
       *  start a new nested list by indenting further, 2 or 3 spaces     
    +  Always add two spaces at the end of each line    
    -  List bullets will vary by indentation automatically
    + [x] Can make checklists using `[ ]` and `[x]` but buttons aren't reactive to clicking.    

---  
  
    
  
#### 4. Build website  
  
*  Once you're done adding content and editing, you'll want to 'Knit' everything then go to the 'Build' tab and click 'Build Website'.
  
---
  
  
#### 5. Customize styles

+ adding a Bootstrap theme is easy: just change the name of theme in the header of the Rmd file (see below). Beyond that, you'll need to add other elements of the `styles.css` file.


+ If you want to further customize, you'd need to edit the css formatting in a new file:
  - create a file called styles.css in your websites' working directory.
  - add css formatting parameters (beyond the scope of this document but many sources online).
  - add `css: style.css` to the end of the .yml file in `output` to modify the bootstrap theme or create entirely custom layout/theme.


```
output:
  html_document:
    theme: lumen
    highlight: textmate
    css: style.css
```  
  
  
---
  
  
#### 6. Push to Git

*Using git command line*
 -  Open a terminal window, set working directory to your project folder
 -  Enter these commands in (after $):

- Using bash:  

        to see all available Git commands:
           $ git
           
        add the files in the directory to the index  
           $ git add .
           
        log changes and label the commit
           $ git commit -m "first build"
           
        now push changes
           $ git push

 *or in Rstudio*
    - go to 'git' tab in one of the Rstudio panes
    - all new files in the R project working directory should show up here
    - Check each file to include in the 'Staged' column
    - 'Commit' to these changes
    - 'Push' the changes to the git repository
  
 Your site should now be up at your_user_name.github.io within a couple minutes. Nice work! 
  
  
---
  
    
### Troubleshooting
  

#### If you need a new SSH key on Github  
  
  
  I followed [this tutorial](https://help.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) to generate a new SSH key on Github for the first time.

While doing that, you might run into an issue with this if you are on macOS > 10.12. (see next section)
<br>  

  
***

#### Problem encountered while setting SSH key for Github to Rstudio:
  
  
I get to this step where I need to modify the ‘.ssh/config’ file:  
      
    If you're using macOS Sierra 10.12.2 or later, you will need to modify your ~/.ssh/config file to automatically load keys into the ssh-agent and store passphrases in your keychain.
            
            Host *
              AddKeysToAgent yes
              UseKeychain yes
              IdentityFile ~/.ssh/id_ra

I’m using OSx10.12.6, so I found a good answer on StackOverflow and do this stuff
    
        Start Terminal and create the ~/.ssh directory if it doesn't exist:
        	$ mkdir -p ~/.ssh
        
        Now go into the directory:
        	$ cd ~/.ssh
        
        Now open the file config with the default editor:
        	$ open -t config
        
        If it says that file doesn't exist, create it with:
        	$ touch config
        
        and try opening again:
         	$ open -t config
        
        When you edit the file, make sure it is "Plain Text" using the menu at the top of the screen and clicking Format->Make Plain Text.
        Set the permissions as instructed in your tutorial.

Finish that GitHub tutorial and go to the next page to copy SSH info and add it into Github.
This was fine using this:

    	This copies the contents of the id_rsa.pub file to your clipboard
        	$ pbcopy < ~/.ssh/id_rsa.pub
    
Now I can ‘Clone’ the repository by copying the SSH link from my github repository jmoggridge.github.io
